namespace CMG.Commands;

internal sealed record RunGifSettings(
    string? Quality = null,
    int? PointerDuration = null,
    string? PointerSpeed = null,
    string? PointerEasing = null,
    string? ClickPulse = null,
    int? Fps = null,
    int? FrameDelay = null,
    string? Crop = null,
    int? CropPadding = null,
    double? Scale = null,
    int? MaxWidth = null,
    int? MaxHeight = null,
    string? Viewport = null,
    double? PixelRatio = null,
    int? SafeArea = null,
    int? LayoutStability = null,
    string? CaptionStyle = null,
    string? CaptionPosition = null,
    string? CaptionSeverity = null,
    string? CaptionSize = null,
    bool? AutoCaptions = null,
    string? CaptionTemplate = null,
    IReadOnlyList<string>? Redact = null,
    IReadOnlyList<string>? Mask = null,
    IReadOnlyList<string>? Blur = null,
    string? AutoRedact = null,
    string? RedactionSafety = null)
{
    public static RunGifSettings Empty { get; } = new();

    public RunGifSettings Overlay(RunGifSettings? child) => child is null ? this : new(
        child.Quality ?? Quality,
        child.PointerDuration ?? PointerDuration,
        child.PointerSpeed ?? PointerSpeed,
        child.PointerEasing ?? PointerEasing,
        child.ClickPulse ?? ClickPulse,
        child.Fps ?? Fps,
        child.FrameDelay ?? FrameDelay,
        child.Crop ?? Crop,
        child.CropPadding ?? CropPadding,
        child.Scale ?? Scale,
        child.MaxWidth ?? MaxWidth,
        child.MaxHeight ?? MaxHeight,
        child.Viewport ?? Viewport,
        child.PixelRatio ?? PixelRatio,
        child.SafeArea ?? SafeArea,
        child.LayoutStability ?? LayoutStability,
        child.CaptionStyle ?? CaptionStyle,
        child.CaptionPosition ?? CaptionPosition,
        child.CaptionSeverity ?? CaptionSeverity,
        child.CaptionSize ?? CaptionSize,
        child.AutoCaptions ?? AutoCaptions,
        child.CaptionTemplate ?? CaptionTemplate,
        child.Redact ?? Redact,
        child.Mask ?? Mask,
        child.Blur ?? Blur,
        child.AutoRedact ?? AutoRedact,
        child.RedactionSafety ?? RedactionSafety);
}
