namespace CMG.Commands;

internal sealed record RunGifSettings(
    string? Quality = null,
    int? PointerDuration = null,
    string? PointerSpeed = null,
    string? PointerEasing = null,
    string? PointerPath = null,
    string? DragPath = null,
    string? ClickPulse = null,
    int? Fps = null,
    int? FrameDelay = null,
    string? Crop = null,
    int? CropPadding = null,
    string? SmartCrop = null,
    string? SplitTabs = null,
    double? Scale = null,
    int? MaxWidth = null,
    int? MaxHeight = null,
    string? Viewport = null,
    double? PixelRatio = null,
    int? SafeArea = null,
    int? LayoutStability = null,
    string? TargetZoom = null,
    int? TargetZoomThreshold = null,
    string? PagePosition = null,
    string? TabContext = null,
    string? CaptionStyle = null,
    string? CaptionPosition = null,
    string? CaptionSeverity = null,
    string? CaptionSize = null,
    bool? AutoCaptions = null,
    string? CaptionTemplate = null,
    IReadOnlyList<string>? Redact = null,
    IReadOnlyList<string>? Mask = null,
    IReadOnlyList<string>? Blur = null,
    string? AutoRedact = null,
    string? RedactionSafety = null,
    string? SizeBudget = null,
    bool? BudgetQualityFallback = null,
    bool? BudgetDownscaleFallback = null,
    string? NarrationSidecar = null,
    string? AltText = null,
    string? Description = null)
{
    public static RunGifSettings Empty { get; } = new();

    public RunGifSettings Overlay(RunGifSettings? child) => child is null ? this : new(
        child.Quality ?? Quality,
        child.PointerDuration ?? PointerDuration,
        child.PointerSpeed ?? PointerSpeed,
        child.PointerEasing ?? PointerEasing,
        child.PointerPath ?? PointerPath,
        child.DragPath ?? DragPath,
        child.ClickPulse ?? ClickPulse,
        child.Fps ?? Fps,
        child.FrameDelay ?? FrameDelay,
        child.Crop ?? Crop,
        child.CropPadding ?? CropPadding,
        child.SmartCrop ?? SmartCrop,
        child.SplitTabs ?? SplitTabs,
        child.Scale ?? Scale,
        child.MaxWidth ?? MaxWidth,
        child.MaxHeight ?? MaxHeight,
        child.Viewport ?? Viewport,
        child.PixelRatio ?? PixelRatio,
        child.SafeArea ?? SafeArea,
        child.LayoutStability ?? LayoutStability,
        child.TargetZoom ?? TargetZoom,
        child.TargetZoomThreshold ?? TargetZoomThreshold,
        child.PagePosition ?? PagePosition,
        child.TabContext ?? TabContext,
        child.CaptionStyle ?? CaptionStyle,
        child.CaptionPosition ?? CaptionPosition,
        child.CaptionSeverity ?? CaptionSeverity,
        child.CaptionSize ?? CaptionSize,
        child.AutoCaptions ?? AutoCaptions,
        child.CaptionTemplate ?? CaptionTemplate,
        child.Redact ?? Redact,
        child.Mask ?? Mask,
        child.Blur ?? Blur,
        child.AutoRedact ?? AutoRedact,
        child.RedactionSafety ?? RedactionSafety,
        child.SizeBudget ?? SizeBudget,
        child.BudgetQualityFallback ?? BudgetQualityFallback,
        child.BudgetDownscaleFallback ?? BudgetDownscaleFallback,
        child.NarrationSidecar ?? NarrationSidecar,
        child.AltText ?? AltText,
        child.Description ?? Description);
}
